# Generated by Django 5.0.2 on 2024-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomised',
            name='temporary_password',
            field=models.CharField(default='3OBW*R9!93gz', max_length=64, verbose_name='Mot de passe temporaire'),
        ),
    ]
