# Generated by Django 5.0.2 on 2024-04-07 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('feed_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='subscribed_feeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('image_url', models.URLField(blank=True)),
                ('author', models.TextField()),
                ('content', models.TextField()),
                ('categories', models.ManyToManyField(to='Articles.category')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.rssfeed')),
            ],
        ),
    ]
