# Generated by Django 5.0.2 on 2024-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/1200px-Feed-icon.svg.png', unique=True),
        ),
    ]
