# Generated by Django 5.0.2 on 2024-04-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_rssfeed_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/1200px-Feed-icon.svg.png'),
        ),
    ]
